site_name: The Internals of ksqlDB
site_url: https://books.japila.pl/ksqldb-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of ksqlDB

repo_name: ksqldb-internals
repo_url: https://github.com/japila-books/ksqldb-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags:
  #     tags_file: tags.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: ksqlDB
    kafka: https://books.japila.pl/kafka-internals
    kafka_streams: https://books.japila.pl/kafka-streams-internals
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
  kafka:
    version: 3.0.0
    github: https://github.com/apache/kafka/tree/3.0.0
  ksqldb:
    version: 0.23.1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - DataSource: DataSource.md
    - DataSourceNode: DataSourceNode.md
    - EngineContext: EngineContext.md
    - EngineExecutor: EngineExecutor.md
    - ExecutionStep: ExecutionStep.md
    - ExecutionStepFactory: ExecutionStepFactory.md
    - Format: Format.md
    - FormatFactory: FormatFactory.md
    - Injector: Injector.md
    - JoinNode: JoinNode.md
    - KafkaStreamsBuilder: KafkaStreamsBuilder.md
    - KafkaStreamsBuilderImpl: KafkaStreamsBuilderImpl.md
    - KSPlanBuilder: KSPlanBuilder.md
    - KsqlConfig: KsqlConfig.md
    - KsqlEngine: KsqlEngine.md
    - KsqlExecutionContext: KsqlExecutionContext.md
    - PlanBuilder: PlanBuilder.md
    - PlanInfoExtractor: PlanInfoExtractor.md
    - PlanNode: PlanNode.md
    - QueryApplicationId: QueryApplicationId.md
    - QueryBuilder: QueryBuilder.md
    - QueryBuilderFactory: QueryBuilderFactory.md
    - QueryEngine: QueryEngine.md
    - QueryEventListener: QueryEventListener.md
    - QueryLogger: QueryLogger.md
    - QueryMetadata: QueryMetadata.md
    - QueryMetadataImpl: QueryMetadataImpl.md
    - QueryRegistry: QueryRegistry.md
    - QueryRegistryImpl: QueryRegistryImpl.md
    - PersistentQueryMetadata: PersistentQueryMetadata.md
    - PersistentQueryMetadataImpl: PersistentQueryMetadataImpl.md
    - SandboxedExecutionContext: SandboxedExecutionContext.md
    - SchemaKSourceFactory: SchemaKSourceFactory.md
    - SchemaKStream: SchemaKStream.md
    - ServiceContext: ServiceContext.md
    - SessionConfig: SessionConfig.md
    - SharedKafkaStreamsRuntime: SharedKafkaStreamsRuntime.md
    - SharedKafkaStreamsRuntimeImpl: SharedKafkaStreamsRuntimeImpl.md
    - SingleSourcePlanNode: SingleSourcePlanNode.md
    - SourceBuilder: SourceBuilder.md
    - SourceBuilderBase: SourceBuilderBase.md
    - SourceBuilderV1: SourceBuilderV1.md
    - SourceStep: SourceStep.md
    - SqlPrimitiveType: SqlPrimitiveType.md
    - SqlTypeParser: SqlTypeParser.md
    - StreamSource: StreamSource.md
    - TransientQueryMetadata: TransientQueryMetadata.md
    - VersionCheckerAgent: VersionCheckerAgent.md
  - Query Parsing:
    - parser/index.md
    - AstBuilder:
      - AstBuilder: parser/AstBuilder.md
      - Visitor: parser/AstBuilder_Visitor.md
    - AstVisitor: parser/AstVisitor.md
    - CommonCreateConfigs: parser/CommonCreateConfigs.md
    - CreateSource:
      - CreateSource: parser/CreateSource.md
      - CreateSourceProperties: parser/CreateSourceProperties.md
    - CreateTable: parser/CreateTable.md
    - DdlStatement:
      - DdlStatement: parser/DdlStatement.md
      - ExecutableDdlStatement: parser/ExecutableDdlStatement.md
    - DefaultKsqlParser: parser/DefaultKsqlParser.md
    - DefaultTraversalVisitor: parser/DefaultTraversalVisitor.md
    - KsqlParser: parser/KsqlParser.md
    - Tree Nodes:
      - AstNode: parser/AstNode.md
      - CreateAsSelect: parser/CreateAsSelect.md
      - CreateSourceAsProperties: parser/CreateSourceAsProperties.md
      - CreateStream: parser/CreateStream.md
      - Explain: parser/Explain.md
      - Expression: parser/Expression.md
      - InsertInto: parser/InsertInto.md
      - KsqlWindowExpression: parser/KsqlWindowExpression.md
      - Node: parser/Node.md
      - Statement: parser/Statement.md
      - Query: parser/Query.md
      - QueryContainer: parser/QueryContainer.md
    - SourceAccumulator: parser/SourceAccumulator.md
    - SourcePropertiesUtil: parser/SourcePropertiesUtil.md
    - VariableSubstitutor: parser/VariableSubstitutor.md
  - Query Planning:
    - query-planning/index.md
    - Analysis:
      - Analysis: Analysis.md
      - ImmutableAnalysis: ImmutableAnalysis.md
      - RewrittenAnalysis: RewrittenAnalysis.md
    - Analyzer:
      - Analyzer: Analyzer.md
      - Visitor: Analyzer_Visitor.md
    - AstSanitizer: AstSanitizer.md
    - CommandFactories: CommandFactories.md
    - CreateSourceCommand: CreateSourceCommand.md
    - CreateSourceFactory: CreateSourceFactory.md
    - CreateStreamCommand: CreateStreamCommand.md
    - DataSourceExtractor: DataSourceExtractor.md
    - DdlCommand: DdlCommand.md
    - DdlCommandFactory: DdlCommandFactory.md
    - Executor: Executor.md
    - ExpressionRewriterPlugin: ExpressionRewriterPlugin.md
    - FlatMapNode: FlatMapNode.md
    - KsqlPlan: KsqlPlan.md
    - KsqlPlanV1: KsqlPlanV1.md
    - KsqlStructuredDataOutputNode: KsqlStructuredDataOutputNode.md
    - LogicalPlanner: LogicalPlanner.md
    - MetaStore: MetaStore.md
    - OutputNode: OutputNode.md
    - PhysicalPlan: PhysicalPlan.md
    - PhysicalPlanBuilder: PhysicalPlanBuilder.md
    - PullQueryValidator: PullQueryValidator.md
    - RewriterPlugin: RewriterPlugin.md
    - QueryAnalyzer: QueryAnalyzer.md
    - QueryPlan: QueryPlan.md
    - QueryPlannerOptions: QueryPlannerOptions.md
    - QueryValidator: QueryValidator.md
    - RuntimeBuildContext: RuntimeBuildContext.md
    - UserFunctionLoader: UserFunctionLoader.md
  - REST:
    - Command: rest/Command.md
    - CommandQueue: rest/CommandQueue.md
    - CommandRunner: rest/CommandRunner.md
    - CommandStore: rest/CommandStore.md
    - CustomExecutors: rest/CustomExecutors.md
    - DistributingExecutor: rest/DistributingExecutor.md
    - Executable: rest/Executable.md
    - ExplainExecutor: rest/ExplainExecutor.md
    - InteractiveStatementExecutor: rest/InteractiveStatementExecutor.md
    - InternalKsqlClientFactory: rest/InternalKsqlClientFactory.md
    - KsqlConfigurable: rest/KsqlConfigurable.md
    - KsqlResource: rest/KsqlResource.md
    - KsqlRestApplication: rest/KsqlRestApplication.md
    - KsqlRestConfig: rest/KsqlRestConfig.md
    - KsqlServerEndpoints: rest/KsqlServerEndpoints.md
    - KsqlServerMain: rest/KsqlServerMain.md
    - ProcessingLogServerUtils: rest/ProcessingLogServerUtils.md
    - QueryExecutor: rest/QueryExecutor.md
    - RequestHandler: rest/RequestHandler.md
    - RequestValidator: rest/RequestValidator.md
    - ReservedInternalTopics: rest/ReservedInternalTopics.md
    - ServerOptions: rest/ServerOptions.md
    - StandaloneExecutor:
      - StandaloneExecutor: rest/StandaloneExecutor.md
      - StatementExecutor: rest/StandaloneExecutor_StatementExecutor.md
    - StandaloneExecutorFactory: rest/StandaloneExecutorFactory.md
    - StatementExecutor: rest/StatementExecutor.md
    - ValidatedCommandFactory: rest/ValidatedCommandFactory.md
  - CLI:
    - Cli: cli/Cli.md
    - Ksql: cli/Ksql.md
  - Embedded:
    - EmbeddedKsql: embedded/EmbeddedKsql.md
    - KsqlContext: embedded/KsqlContext.md
  - Misc:
    - Debugging ksqlDB: debugging.md
    - Persistent Queries: persistent-queries.md
