site_name: The Internals of ksqlDB
site_url: https://books.japila.pl/ksqldb-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of ksqlDB

repo_name: ksqldb-internals
repo_url: https://github.com/japila-books/ksqldb-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2022 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: ksqlDB
    kafka: https://books.japila.pl/kafka-internals
    kafka_streams: https://books.japila.pl/kafka-streams-internals
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
  kafka:
    version: 3.2.1
    github: https://github.com/apache/kafka/tree/3.2.1
    api: https://kafka.apache.org/32/javadoc/
  ksqldb:
    docs: https://docs.ksqldb.io/en/0.27.2-ksqldb
    github: https://github.com/confluentinc/ksql/blob/v0.27.2
    version: 0.27.2
    version_major: 0.27
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
  vertx:
    api: https://vertx.io/docs/3.9.12/apidocs

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - Server Properties: server-properties.md
    - AlterSourceFactory: AlterSourceFactory.md
    - DataSource:
      - DataSource: DataSource.md
      - KsqlStream: KsqlStream.md
      - StructuredDataSource: StructuredDataSource.md
    - DdlCommandExec:
      - DdlCommandExec: DdlCommandExec.md
      - DdlCommandExec.Executor: DdlCommandExec.Executor.md
    - EngineContext: EngineContext.md
    - EngineExecutor: EngineExecutor.md
    - ExecutionPlanBuilder: ExecutionPlanBuilder.md
    - ExecutionPlanner: ExecutionPlanner.md
    - ExecutionSteps:
      - ExecutionStep: ExecutionStep.md
      - SourceStep: SourceStep.md
      - StreamSelect: StreamSelect.md
    - ExecutionStepFactory: ExecutionStepFactory.md
    - Formats:
      - Format: Format.md
      - FormatFactory: FormatFactory.md
      - KafkaFormat: KafkaFormat.md
      - KafkaSerdeFactory: KafkaSerdeFactory.md
    - FunctionRegistry: FunctionRegistry.md
    - GenericSerdeFactory: GenericSerdeFactory.md
    - HARouting: HARouting.md
    - ImmutableProperties: ImmutableProperties.md
    - Injectors:
      - DefaultSchemaInjector: DefaultSchemaInjector.md
      - Injector: Injector.md
      - Injectors: Injectors.md
      - SchemaRegisterInjector: SchemaRegisterInjector.md
    - KafkaStreamsBuilder: KafkaStreamsBuilder.md
    - KafkaStreamsBuilderImpl: KafkaStreamsBuilderImpl.md
    - KafkaTopicClientImpl: KafkaTopicClientImpl.md
    - KeyFormat: KeyFormat.md
    - KeySerdeFactory:
      - GenericKeySerDe: GenericKeySerDe.md
      - KeySerdeFactory: KeySerdeFactory.md
    - KSPlanBuilder: KSPlanBuilder.md
    - KsqlConfig: KsqlConfig.md
    - KsqlEngine:
      - KsqlEngine: KsqlEngine.md
      - KsqlEngineMetrics: KsqlEngineMetrics.md
    - KsqlExecutionContext: KsqlExecutionContext.md
    - KsqlSchemaRegistryClientFactory: KsqlSchemaRegistryClientFactory.md
    - KsqlQueryType: KsqlQueryType.md
    - LogicalSchema: LogicalSchema.md
    - MetaStore:
      - MetaStore: MetaStore.md
      - MetaStoreImpl: MetaStoreImpl.md
      - MutableMetaStore: MutableMetaStore.md
    - PersistentQueryMetadata: PersistentQueryMetadata.md
    - PersistentQueryMetadataImpl: PersistentQueryMetadataImpl.md
    - PhysicalPlanner: PhysicalPlanner.md
    - PlanBuilder: PlanBuilder.md
    - PlanInfoExtractor: PlanInfoExtractor.md
    - PullPhysicalPlanBuilder: PullPhysicalPlanBuilder.md
    - PullQueryExecutionUtil: PullQueryExecutionUtil.md
    - PushQueryMetadata: PushQueryMetadata.md
    - PushRouting: PushRouting.md
    - QueryApplicationId: QueryApplicationId.md
    - QueryBuilder: QueryBuilder.md
    - QueryBuilderFactory: QueryBuilderFactory.md
    - QueryEngine: QueryEngine.md
    - QueryEventListener: QueryEventListener.md
    - QueryLogger: QueryLogger.md
    - QueryMetadata: QueryMetadata.md
    - QueryMetadataImpl: QueryMetadataImpl.md
    - QueryRegistry: QueryRegistry.md
    - QueryRegistryImpl: QueryRegistryImpl.md
    - QueryStateMetricsReportingListener: QueryStateMetricsReportingListener.md
    - RouteQuery: RouteQuery.md
    - RowDeserializer: RowDeserializer.md
    - SandboxedExecutionContext: SandboxedExecutionContext.md
    - SandboxedServiceContext: SandboxedServiceContext.md
    - SchemaKSourceFactory: SchemaKSourceFactory.md
    - SchemaKStream: SchemaKStream.md
    - SchemaKTable: SchemaKTable.md
    - SerdeFeaturesFactory: SerdeFeaturesFactory.md
    - ServiceContext: ServiceContext.md
    - ServiceContextFactory: ServiceContextFactory.md
    - ServiceInfo: ServiceInfo.md
    - SessionConfig: SessionConfig.md
    - SharedKafkaStreamsRuntime: SharedKafkaStreamsRuntime.md
    - SharedKafkaStreamsRuntimeImpl: SharedKafkaStreamsRuntimeImpl.md
    - SourceBuilder: SourceBuilder.md
    - SourceBuilderBase: SourceBuilderBase.md
    - SourceBuilderV1: SourceBuilderV1.md
    - SqlTypeParser: SqlTypeParser.md
    - StatementRewriter:
      - StatementRewriter: StatementRewriter.md
      - StatementRewriter.Rewriter: StatementRewriter.Rewriter.md
    - StreamSelectBuilder: StreamSelectBuilder.md
    - StreamSource: StreamSource.md
    - SystemColumns: SystemColumns.md
    - TransientQueryMetadata: TransientQueryMetadata.md
    - TypeRegistry: TypeRegistry.md
    - ValueSerdeFactory:
      - GenericRowSerDe: GenericRowSerDe.md
      - ValueSerdeFactory: ValueSerdeFactory.md
    - VersionCheckerAgent: VersionCheckerAgent.md
  - Features:
    - features/index.md
    - Data Types:
      - SqlBaseType: types/SqlBaseType.md
      - SqlPrimitiveType: types/SqlPrimitiveType.md
      - SqlType: types/SqlType.md
    - Execution Modes:
      - Embedded:
        - embedded/index.md
        - KsqlContext: embedded/KsqlContext.md
      - Headless:
        - headless/index.md
        - ConfigStore: headless/ConfigStore.md
        - KafkaConfigStore: headless/KafkaConfigStore.md
        - StandaloneExecutor: headless/StandaloneExecutor.md
        - StandaloneExecutorFactory: headless/StandaloneExecutorFactory.md
        - StatementExecutor: headless/StandaloneExecutor_StatementExecutor.md
      - REST:
        - rest/index.md
    - Metrics:
      - metrics/index.md
      - ConsumerCollector: metrics/ConsumerCollector.md
      - KsqlMetricsExtension: metrics/KsqlMetricsExtension.md
      - LogMetricAndContinueExceptionHandler: metrics/LogMetricAndContinueExceptionHandler.md
      - MetricCollector: metrics/MetricCollector.md
      - MetricCollectors: metrics/MetricCollectors.md
      - ProducerCollector: metrics/ProducerCollector.md
      - StreamsErrorCollector: metrics/StreamsErrorCollector.md
    - Monitoring:
      - ProcessingLogConfig: monitoring/ProcessingLogConfig.md
      - ProcessingLogContext: monitoring/ProcessingLogContext.md
    - Persistent Queries: persistent-queries.md
    - Processing Log: processing-log.md
    - Pull Queries: pull-queries.md
    - Push Queries: push-queries.md
    - UDFs:
      - Column: udf/Column.md
      - SqlTypeSchemaSerializer: udf/SqlTypeSchemaSerializer.md
    - Security:
      - security/index.md
      - KsqlAccessValidator: security/KsqlAccessValidator.md
      - KsqlAuthorizationProvider: security/KsqlAuthorizationProvider.md
      - KsqlAuthorizationValidator: security/KsqlAuthorizationValidator.md
      - KsqlAuthorizationValidatorFactory: security/KsqlAuthorizationValidatorFactory.md
      - KsqlAuthorizationValidatorImpl: security/KsqlAuthorizationValidatorImpl.md
      - KsqlSecurityExtension: security/KsqlSecurityExtension.md
      - KsqlDefaultSecurityExtension: security/KsqlDefaultSecurityExtension.md
  - Statement Parsing:
    - parser/index.md
    - AST Tree Nodes:
      - AlterSource: parser/AlterSource.md
      - AlterSystemProperty: parser/AlterSystemProperty.md
      - AssertStatement: parser/AssertStatement.md
      - AstNode: parser/AstNode.md
      - CreateAsSelect: parser/CreateAsSelect.md
      - CreateSourceAsProperties: parser/CreateSourceAsProperties.md
      - CreateStream: parser/CreateStream.md
      - CreateStreamAsSelect: parser/CreateStreamAsSelect.md
      - CreateTableAsSelect: parser/CreateTableAsSelect.md
      - DescribeTables: parser/DescribeTables.md
      - Explain: parser/Explain.md
      - Expression: parser/Expression.md
      - InsertInto: parser/InsertInto.md
      - KsqlWindowExpression: parser/KsqlWindowExpression.md
      - ListStreams: parser/ListStreams.md
      - Node: parser/Node.md
      - PrintTopic: parser/PrintTopic.md
      - Query: parser/Query.md
      - QueryContainer: parser/QueryContainer.md
      - ShowColumns: parser/ShowColumns.md
      - Sink: parser/Sink.md
      - Statement: parser/Statement.md
      - StatementWithExtendedClause: parser/StatementWithExtendedClause.md
      - WindowExpression: parser/WindowExpression.md
    - AstBuilder:
      - AstBuilder: parser/AstBuilder.md
      - AstBuilder.Visitor: parser/AstBuilder.Visitor.md
    - AstVisitor: parser/AstVisitor.md
    - CommonCreateConfigs: parser/CommonCreateConfigs.md
    - CreateSource:
      - CreateSource: parser/CreateSource.md
      - CreateSourceProperties: parser/CreateSourceProperties.md
    - CreateTable: parser/CreateTable.md
    - DdlStatement:
      - DdlStatement: parser/DdlStatement.md
      - ExecutableDdlStatement: parser/ExecutableDdlStatement.md
    - DefaultKsqlParser: parser/DefaultKsqlParser.md
    - DefaultTraversalVisitor: parser/DefaultTraversalVisitor.md
    - KsqlParser: parser/KsqlParser.md
    - SourceAccumulator: parser/SourceAccumulator.md
    - SourcePropertiesUtil: parser/SourcePropertiesUtil.md
    - TerminateQuery: parser/TerminateQuery.md
    - VariableSubstitutor: parser/VariableSubstitutor.md
  - Statement Analysis:
    - analyzer/index.md
    - Analysis: analyzer/Analysis.md
    - Analyzer:
      - Analyzer: analyzer/Analyzer.md
      - Analyzer.Visitor: analyzer/Analyzer.Visitor.md
    - ImmutableAnalysis: analyzer/ImmutableAnalysis.md
    - PullQueryValidator: analyzer/PullQueryValidator.md
    - QueryAnalyzer: analyzer/QueryAnalyzer.md
    - QueryValidator: analyzer/QueryValidator.md
    - RewrittenAnalysis: analyzer/RewrittenAnalysis.md
  - Statement Planning:
    - planner/index.md
    - AstSanitizer:
      - AstSanitizer: AstSanitizer.md
      - AstSanitizer.RewriterPlugin: AstSanitizer.RewriterPlugin.md
    - CommandFactories: CommandFactories.md
    - ConfiguredKsqlPlan: ConfiguredKsqlPlan.md
    - CreateSourceCommand: CreateSourceCommand.md
    - CreateSourceFactory: CreateSourceFactory.md
    - DataSourceExtractor: DataSourceExtractor.md
    - DdlCommands:
      - AlterSourceCommand: AlterSourceCommand.md
      - CreateStreamCommand: CreateStreamCommand.md
      - CreateTableCommand: CreateTableCommand.md
      - DdlCommand: DdlCommand.md
      - DropSourceCommand: DropSourceCommand.md
      - DropTypeCommand: DropTypeCommand.md
      - RegisterTypeCommand: RegisterTypeCommand.md
    - DdlCommandFactory: DdlCommandFactory.md
    - Executor: Executor.md
    - ExpressionRewriterPlugin: ExpressionRewriterPlugin.md
    - KsqlPlan: KsqlPlan.md
    - KsqlPlanV1: KsqlPlanV1.md
    - LogicalPlanner: planner/LogicalPlanner.md
    - PhysicalPlan: PhysicalPlan.md
    - Logical Plan Nodes:
      - DataSourceNode: planner/DataSourceNode.md
      - FlatMapNode: planner/FlatMapNode.md
      - JoinNode: planner/JoinNode.md
      - KsqlBareOutputNode: planner/KsqlBareOutputNode.md
      - KsqlStructuredDataOutputNode: planner/KsqlStructuredDataOutputNode.md
      - OutputNode: planner/OutputNode.md
      - PlanNode: planner/PlanNode.md
      - ProjectNode: planner/ProjectNode.md
      - QueryProjectNode: planner/QueryProjectNode.md
      - SingleSourcePlanNode: planner/SingleSourcePlanNode.md
    - QueryPlan: QueryPlan.md
    - QueryPlannerOptions: planner/QueryPlannerOptions.md
    - RuntimeBuildContext: RuntimeBuildContext.md
    - UserFunctionLoader: UserFunctionLoader.md
  - REST:
    - rest/index.md
    - Command: rest/Command.md
    - CommandIdAssigner: rest/CommandIdAssigner.md
    - CommandQueue: rest/CommandQueue.md
    - CommandRunner:
      - CommandRunner: rest/CommandRunner.md
      - CommandRunnerMetrics: rest/CommandRunnerMetrics.md
    - CommandStore:
      - CommandStore: rest/CommandStore.md
      - CommandStoreUtil: rest/CommandStoreUtil.md
    - CommandTopic: rest/CommandTopic.md
    - CommandTopicBackup: rest/CommandTopicBackup.md
    - CustomExecutors: rest/CustomExecutors.md
    - CustomValidators: rest/CustomValidators.md
    - DefaultCommandQueueSync: rest/DefaultCommandQueueSync.md
    - DistributingExecutor: rest/DistributingExecutor.md
    - Executable: rest/Executable.md
    - ExplainExecutor: rest/ExplainExecutor.md
    - InsertsStreamEndpoint: rest/InsertsStreamEndpoint.md
    - InteractiveStatementExecutor: rest/InteractiveStatementExecutor.md
    - InternalKsqlClientFactory: rest/InternalKsqlClientFactory.md
    - KsqlConfigurable: rest/KsqlConfigurable.md
    - KsqlResource: rest/KsqlResource.md
    - KsqlRestApplication: rest/KsqlRestApplication.md
    - KsqlRestConfig: rest/KsqlRestConfig.md
    - KsqlServerEndpoints: rest/KsqlServerEndpoints.md
    - KsqlServerMain: rest/KsqlServerMain.md
    - QueryEndpoint: rest/QueryEndpoint.md
    - QueryExecutor: rest/QueryExecutor.md
    - ProcessingLogServerUtils: rest/ProcessingLogServerUtils.md
    - RecordFormatter: rest/RecordFormatter.md
    - RequestHandler: rest/RequestHandler.md
    - RequestValidator: rest/RequestValidator.md
    - ReservedInternalTopics: rest/ReservedInternalTopics.md
    - RestServiceContextFactory: rest/RestServiceContextFactory.md
    - ScalablePushUtil: rest/ScalablePushUtil.md
    - ServerOptions: rest/ServerOptions.md
    - SequenceNumberFutureStore: rest/SequenceNumberFutureStore.md
    - StatementExecutors:
      - ListSourceExecutor: rest/ListSourceExecutor.md
      - StatementExecutor: rest/StatementExecutor.md
    - StatementParser: rest/StatementParser.md
    - StreamedQueryResource: rest/StreamedQueryResource.md
    - ValidatedCommandFactory: rest/ValidatedCommandFactory.md
    - WSQueryEndpoint: rest/WSQueryEndpoint.md
  - ksql CLI:
    - cli/index.md
    - Cli: cli/Cli.md
    - Ksql: cli/Ksql.md
    - KsqlClient: cli/KsqlClient.md
    - KsqlRestClient: cli/KsqlRestClient.md
  - API:
    - BlockingQueryPublisher: api/BlockingQueryPublisher.md
    - Endpoints: api/Endpoints.md
    - QueryPublisher: api/QueryPublisher.md
    - QueryStreamHandler: api/QueryStreamHandler.md
    - Server: api/Server.md
    - ServerVerticle: api/ServerVerticle.md
  - Misc:
    - Debugging ksqlDB: debugging.md
    - Logging: logging.md
    - KsqlInternalTopicUtils: KsqlInternalTopicUtils.md
    - SlidingWindowRateLimiter: SlidingWindowRateLimiter.md
  - Demos:
    - Confluent Schema Registry: demo/confluent-schema-registry.md
    - Multi-Node ksqlDB Deployment: demo/multi-node-ksqldb-deployment.md
    - Pull Queries: demo/pull-queries.md
    - SHOW STREAMS: demo/show-streams.md
    - CREATE TABLE AS SELECT: demo/create-table-as-select.md
    - Table isn't queryable: demo/table-isnt-queryable.md
    - Dealing with Deserialization Errors: demo/dealing-with-deserialization-errors.md
